TeamThunderFriends/ttf_web_back

src/main/java/ttf/lost/domain/accessory/Accessory.java, src/main/java/ttf/lost/domain/avatar/Avatar.java, src/main/java/ttf/lost/domain/character/Character.java, src/main/java/ttf/lost/domain/equipment/Equipment.java, src/main/java/ttf/lost/domain/gem/Gem.java, src/main/java/ttf/lost/domain/user/User.java, src/main/java/ttf/lost/domain/usercharacter/UserCharacter.java
***
**Changes🔨**
- 엔티티 연관관계 매핑 추가
**To-be🤔**
**Screenshot**
=> [#7] 엔티티 연관관계 매핑 추가

src/main/java/ttf/lost/domain/accessory/Accessory.java, src/main/java/ttf/lost/domain/avatar/Avatar.java, src/main/java/ttf/lost/domain/base/ItemGrade.java, src/main/java/ttf/lost/domain/category/CategoryNumber.java, src/main/java/ttf/lost/domain/character/Character.java, src/main/java/ttf/lost/domain/equipment/Equipment.java, src/main/java/ttf/lost/domain/gem/Gem.java, src/main/java/ttf/lost/domain/material/Materials.java, src/main/java/ttf/lost/domain/skill/SkillNumber.java, src/main/java/ttf/lost/domain/user/User.java, src/main/java/ttf/lost/domain/usercharacter/UserCharacter.java
- 엔티티 연관관계 매핑 필요
***
**Changes🔨**
- 엔티티 연관관계 매핑 작업
**To-be🤔**
- LostArk API Avatar 가져오기 (DTO)
**Screenshot**
=> feat : [#7] 엔티티 연관관계 매핑 추가

src/main/java/ttf/lost/application/user/LostArkUserService.java, src/main/java/ttf/lost/application/user/RedisSessionService.java, src/main/java/ttf/lost/application/user/SessionService.java, src/main/java/ttf/lost/application/user/UserService.java, src/main/java/ttf/lost/application/user/UserServiceFacade.java, src/main/java/ttf/lost/domain/user/User.java, src/main/java/ttf/lost/infrastructure/UserRepository.java, src/main/java/ttf/lost/presentation/api/user/LoginController.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
***
**As-is🔨**
**To-be🤔**
**Screenshot**
=>  [#1,#2] self - 로그인 회원가입 기능

src/main/java/ttf/lost/domain/accessory/Accessory.java, src/main/java/ttf/lost/domain/avatar/Avatar.java, src/main/java/ttf/lost/domain/character/GameCharacter.java, src/main/java/ttf/lost/domain/equipment/Equipment.java, src/main/java/ttf/lost/domain/gem/Gem.java, src/main/java/ttf/lost/domain/usercharacter/UserCharacter.java
- DB 예약어로 인한 테이블 생성이 되지 않는 버그 수정 
***
**As-is🔨**
- class-name : Character
**To-be🤔**
- class-name : GameCharacter 
**Screenshot**
=> [#13] 엔티티 db 예약어 버그 수정

src/main/java/ttf/lost/application/user/LostArkUserService.java, src/main/java/ttf/lost/application/user/RedisSessionService.java, src/main/java/ttf/lost/application/user/SessionService.java, src/main/java/ttf/lost/application/user/UserService.java, src/main/java/ttf/lost/application/user/UserServiceFacade.java, src/main/java/ttf/lost/domain/user/User.java, src/main/java/ttf/lost/infrastructure/UserRepository.java, src/main/java/ttf/lost/presentation/api/user/LoginController.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
- 로그인 회원 가입 기능 추가
***
**As-is🔨**
**To-be🤔**
- 로그인 회원 가입 기능 추가
- 추후에 Controller 인증 관련 로직을 추가해야 할 것으로 보임
**Screenshot**
=> [#1,#2] 로그인 회원가입 기능

src/main/java/ttf/lost/application/user/RedisSessionService.java, src/main/java/ttf/lost/application/user/UserService.java, src/main/java/ttf/lost/presentation/api/user/request/UserRequest.java
***
**As-is🔨**
**To-be🤔**
**Screenshot**
=> [#1,#2] UserRequest 추가

src/main/java/ttf/lost/common/config/RestTemplateConfig.java, src/main/java/ttf/lost/common/exception/ErrorCode.java, src/main/java/ttf/lost/common/exception/GlobalException.java, src/main/java/ttf/lost/common/exception/GlobalExceptionHandler.java
***
**As-is🔨**
**To-be🤔**
**Screenshot**
=> [#24] self - global exception 수정

src/main/java/ttf/lost/common/config/RestTemplateConfig.java, src/main/java/ttf/lost/common/exception/ErrorCode.java, src/main/java/ttf/lost/common/exception/GlobalException.java, src/main/java/ttf/lost/common/exception/GlobalExceptionHandler.java
- GlobalException 필드 상속필드 사용
- ErrorCode 추가
***
**As-is🔨**
- custom field 사용 (loggingErrorMessage)
**To-be🤔**
- Exception 상속 필드 사용(message)
**Screenshot**
=> Feature/global exception 수정 #24

src/main/java/ttf/lost/common/annotation/JsonPaths.java, src/main/java/ttf/lost/common/utils/LostArkAPIResponseParser.java, src/main/java/ttf/lost/common/utils/RedisKeyUtils.java
***
**As-is🔨**
**To-be🤔**
**Screenshot**
=> [#27] self-lost ark api 응답 파서 생성

src/main/java/ttf/lost/common/annotation/JsonPaths.java, src/main/java/ttf/lost/common/utils/LostArkAPIResponseParser.java, src/main/java/ttf/lost/common/utils/RedisKeyUtils.java
- 로스트아크 api 응답 parser 추가
***
**As-is🔨**
**To-be🤔**
**Screenshot**
=> [#27] lost ark api 응답 파서 생성

src/main/java/ttf/lost/application/avatar/AvatarService.java, src/main/java/ttf/lost/application/avatar/AvatarServiceFacade.java, src/main/java/ttf/lost/application/avatar/LostArkAvatarService.java, src/main/java/ttf/lost/infrastructure/api/avatar/AvatarAPIClient.java, src/main/java/ttf/lost/infrastructure/api/avatar/AvatarDto.java, src/main/java/ttf/lost/infrastructure/api/avatar/LostArkUserAvatarAPI.java, src/main/java/ttf/lost/presentation/api/avatar/AvatarController.java, src/main/java/ttf/lost/presentation/api/avatar/response/AvatarDtoResponse.java
***
**As-is🔨**
**To-be🤔**
**Screenshot**
=> [#12] self - Open API 불러온 후 DTO 변환 기능 추가

src/main/java/ttf/lost/common/exception/ErrorResponse.java, src/main/resources/templates/character/authentication.html, src/main/resources/templates/user/login.html
- test 용  view 추가 추후에 디자인 변경
***
**As-is🔨**
**To-be🤔**
**Screenshot**
=> [#3] self - 계정 인증 test view 생성

src/main/java/ttf/lost/application/user/AuthService.java, src/main/java/ttf/lost/application/user/SessionService.java, src/main/java/ttf/lost/application/user/UserService.java, src/main/java/ttf/lost/infrastructure/api/user/UserAPIClient.java, src/main/java/ttf/lost/infrastructure/repository/user/AuthenticationRepository.java, src/main/java/ttf/lost/infrastructure/repository/user/UserRepository.java
***
**As-is🔨**
**To-be🤔**
**Screenshot**
=> [#3] self - 인증 인터페이스 정의

src/main/java/ttf/lost/common/config/RestTemplateConfig.java, src/main/resources/application.yml
***
**As-is🔨**
**To-be🤔**
**Screenshot**
=> [#39] self - api key 설정 추가

src/main/java/ttf/lost/common/config/RestTemplateConfig.java, src/main/resources/application.yml
- LOST ARK API 키 설정 추가
***
**As-is🔨**
**To-be🤔**
- RestTemplate에서 헤더를 추가 해서 사용하도록 설정 변경
**Screenshot**
=> [#39] 로스트아크 api key 설정 추가

src/main/java/ttf/lost/application/avatar/AvatarService.java, src/main/java/ttf/lost/application/avatar/AvatarServiceFacade.java, src/main/java/ttf/lost/application/avatar/ClassNameMapConstant.java, src/main/java/ttf/lost/application/avatar/LostArkAvatarService.java, src/main/java/ttf/lost/domain/avatar/Avatar.java, src/main/java/ttf/lost/infrastructure/api/avatar/AvatarAPIClient.java, src/main/java/ttf/lost/infrastructure/api/avatar/AvatarAndPriceDto.java, src/main/java/ttf/lost/infrastructure/api/avatar/AvatarSaveDto.java, src/main/java/ttf/lost/infrastructure/api/avatar/LostArkUserAvatarAPI.java, src/main/java/ttf/lost/infrastructure/repository/avatar/AvatarRepository.java, src/main/java/ttf/lost/presentation/api/avatar/AvatarController.java
-  Avatar List를 받고 Open API 불러와 가격과 같이 DTO 변환
***
**As-is🔨**
**To-be🤔**
- Avatar List를 받고 Open API 불러와 가격과 같이 DTO 변환
**Screenshot**
=> [#12] self - Avatar List를 받고 Open API 불러와 가격과 같이 DTO 변환

src/main/java/ttf/lost/application/avatar/AvatarService.java, src/main/java/ttf/lost/application/avatar/AvatarServiceFacade.java, src/main/java/ttf/lost/application/avatar/LostArkAvatarService.java, src/main/java/ttf/lost/domain/avatar/Avatar.java, src/main/java/ttf/lost/infrastructure/api/avatar/AvatarAndTotalPriceDto.java, src/main/java/ttf/lost/infrastructure/api/avatar/AvatarResponseDto.java, src/main/java/ttf/lost/presentation/api/avatar/AvatarController.java
- Avatar 정보와 Price, total 반환 기능 추가
***
**As-is🔨**
**To-be🤔**
- Avatar 정보와 Price, total 반환 기능 추가
**Screenshot**
=> [#43] self - Avatar 정보와 Price, total 반환 기능 추가

src/main/java/ttf/lost/common/exception/ErrorResponse.java, src/main/resources/templates/character/authentication.html, src/main/resources/templates/user/login.html
- test 용  view 추가 추후에 디자인 변경
***
**As-is🔨**
- 임시용
**To-be🤔**
- 퍼블리싱 작업
**Screenshot**
=> [#3]계정 인증 test view 생성

src/main/java/ttf/lost/common/annotation/JsonRoot.java, src/main/java/ttf/lost/common/utils/LostArkAPIResponseParser.java, src/main/java/ttf/lost/infrastructure/api/avatar/AvatarDto.java, src/main/java/ttf/lost/infrastructure/api/avatar/LostArkUserAvatarAPI.java, src/main/resources/application.yml
- 기존에 하드코딩된 json root 분리
***
**As-is🔨**
- json root 하드코딩
**To-be🤔**
- 어노테이션 분리
**Screenshot**
=> [#55] json parser 수정

src/test/java/ttf/lost/LostArkApplicationTest.java, src/test/java/ttf/lost/infrastructure/api/avatar/LostArkUserAvatarAPITest.java
- Avatar Open API DTO 변환 테스트 작성 및 테스트 폴더 생성
***
**As-is🔨**
**To-be🤔**
- Avatar Open API DTO 변환 테스트 작성 및 테스트 폴더 생성
**Screenshot**
=> [#54] Avatar Open API DTO 변환 테스트 작성 및 테스트 폴더 생성
